model = "gpt-5.2-codex"
model_reasoning_effort = "medium"

web_search = "live"

[sandbox_workspace_write]
network_access = true

[notice.model_migrations]
"gpt-5.1-codex-max" = "gpt-5.2-codex"

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp"]

[mcp_servers.nuxt]
command = "npx"
args = ["mcp-remote", "https://nuxt.com/mcp"]

[mcp_servers.nuxt_ui]
command = "npx"
args = ["mcp-remote", "https://ui.nuxt.com/mcp"]

[mcp_servers.playwright]
command = "npx"
args = ["@playwright/mcp@latest", "--extension"]
